#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <jar-name> <options>"
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$SPARK_HOME/bin/spark-submit --master yarn --deploy-mode cluster "$DIR/$1" "${@:2}"
