#!/bin/bash

seconds=60

echo "----- START ----"
echo
while "$@" || true; do
  echo
  echo "----- END ----"
  echo "Run '$1' again in $seconds seconds..."
  sleep $seconds
  echo "----- START ----"
  echo
done
