#!/bin/bash
#
# Disconnect status codes:
# 1  - Shutdown
# 2  - Duplicate stream
# 3  - Control request
# 4  - Stall
# 5  - Normal
# 6  - Token revoked
# 7  - Admin logout
# 9  - Max message limit
# 10 - Stream exception
# 11 - Broker Stall
# 12 - Shed load
#

while IFS='\n' read -r tweet ; do
  if grep -q '^{"created_at"' <<< "$tweet"; then
    echo "$tweet"
    continue
  fi

  printf "\r\e[0KLast control message: " >&2
  if grep -q '^{"disconnect"' <<< "$tweet"; then
    printf "$(jq -Mj '"Disconnect (\(.disconnect.code))"' <<< "$tweet")" >&2
  elif grep -q '^{"warning"' <<< "$tweet"; then
    printf "$(jq -Mj '"Warning (\(.warning.code))"' <<< "$tweet")" >&2
  elif grep -q '^{"limit"' <<< "$tweet"; then
    printf "Limit" >&2
  elif grep -q '^{"scrub_geo"' <<< "$tweet"; then
    printf "Scrub geo" >&2
  elif grep -q '^{"delete"' <<< "$tweet"; then
    printf "Delete" >&2
  else
    printf "Keep-alive" >&2
  fi

  echo "$tweet"
done < "${1:-/dev/stdin}"
