#!/bin/bash
#
# Disconnect status codes:
# 1  - Shutdown
# 2  - Duplicate stream
# 3  - Control request
# 4  - Stall
# 5  - Normal
# 6  - Token revoked
# 7  - Admin logout
# 9  - Max message limit
# 10 - Stream exception
# 11 - Broker Stall
# 12 - Shed load
#

prexif="Last control message:"
while IFS='\n' read -r tweet ; do
  if grep -q '^{"created_at"' <<< "$tweet"; then
    echo "$tweet"
    continue
  fi

  if grep -q '^{"disconnect"' <<< "$tweet"; then
    printf "\r\e[0$prexif $(jq -Mj '"Disconnect (\(.disconnect.code))"' <<< "$tweet")" >&2
  elif grep -q '^{"warning"' <<< "$tweet"; then
    printf "\r\e[0$prexif $(jq -Mj '"Warning (\(.warning.code))"' <<< "$tweet")" >&2
  elif grep -q '^{"limit"' <<< "$tweet"; then
    printf "\r\e[0$prexif Limit" >&2
  elif grep -q '^{"scrub_geo"' <<< "$tweet"; then
    printf "\r\e[0$prexif Scrub geo" >&2
  elif grep -q '^{"delete"' <<< "$tweet"; then
    printf "\r\e[0$prexif Delete" >&2
  else
    printf "\r\e[0$prexif Keep-alive" >&2
  fi

  echo "$tweet"
done < "${1:-/dev/stdin}"
