#!/bin/bash

has_jq=0
if command -v jq >/dev/null 2>&1; then
  has_jq=1
fi

output=
count=0
file=
while getopts 'c:n:f:' arg
do
  case ${arg} in
    c) count="${OPTARG}" ;;
    n) output="${OPTARG}" ;;
    f) file="${OPTARG}" ;;
  esac
done

if [ -z "$output" ]; then
  output="$file"
fi

output_lines=1
if [ -e "$output" ]; then
  output_lines=$((output_lines+1))
fi
if [ "$has_jq" -eq 1 ]; then
  output_lines=$((output_lines+1))
fi
for i in `seq $output_lines`; do echo; done

while IFS='\n' read -r tweet ; do
  count=$((count+1))
  printf "\e[${output_lines}A\r\e[0KTweets collected: $count\n"
  if [ -e "$output" ]; then
    printf "\r\e[0KFile size: $(du -m "$output" | cut -f1)MB\n"
  fi
  if [ "$has_jq" -eq 1 ]; then
    printf "\r\e[0K$(jq -Mj '"Last tweeter: @\(.user.screen_name)"' <<< "$tweet")\n"
  fi
done < "${file:-/dev/stdin}"
